config/routes.rb
Soundexo::Application.routes.draw do
  resources :products


  root :to => "home#index"
end

app/models/product.rb
#-*- encoding: utf-8 -*-
class Product < ActiveRecord::Base
  attr_accessible :description, :title
  acts_as_indexed fields: [:title, :description, :title_phonetized, :description_phonetized]
  acts_as_fulltextable :title, :description, :title_phonetized, :description_phonetized
  phonetized :title
  phonetized :description
  def normalize(str)
    str.tr(
      "ÀÁÂÃÄÅàáâãäåĀāĂăĄąÇçĆćĈĉĊċČčÐðĎďĐđÈÉÊËèéêëĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħÌÍÎÏìíîïĨĩĪīĬĭĮįİıĴĵĶķĸĹĺĻļĽľĿŀŁłÑñŃńŅņŇňŉŊŋÒÓÔÕÖØòóôõöøŌōŎŏŐőŔŕŖŗŘřŚśŜŝŞşŠšſŢţŤťŦŧÙÚÛÜùúûüŨũŪūŬŭŮůŰűŲųŴŵÝýÿŶŷŸŹźŻżŽž",
      "AAAAAAaaaaaaAaAaAaCcCcCcCcCcDdDdDdEEEEeeeeEeEeEeEeEeGgGgGgGgHhHhIIIIiiiiIiIiIiIiIiJjKkkLlLlLlLlLlNnNnNnNnnNnOOOOOOooooooOoOoOoRrRrRrSsSsSsSssTtTtTtUUUUuuuuUuUuUuUuUuUuWwYyyYyYZzZzZz"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index

    @kw = params[:q]
    if @kw.blank?
      @products = @products2 = @products3 = @products4 = Product.all
    else
      @kw_phonetized = @kw.to_sound

      kw_like_query = "%#{@kw}%"
      kw_regex_query = "[[:<:]]#{@kw_phonetized}[[:>:]]"


      # Alternativa #1: qualquer parte da palavra
      @products = Product.where("title LIKE ? OR description LIKE ? OR title_phonetized LIKE ? OR description_phonetized LIKE ?", kw_like_query, kw_like_query, kw_like_query, kw_like_query)

      # Alternativa #2: palavras inteiras
      @products2 = Product.where("title LIKE ? OR description LIKE ? OR title_phonetized REGEXP ? = 1 OR description_phonetized REGEXP ? = 1", kw_like_query, kw_like_query, kw_regex_query, kw_regex_query)

      # Alternativa #3: com acts_as_indexed
      @products3 = (Product.find_with_index(@kw) + Product.find_with_index(@kw_phonetized)).uniq

      # Alternativa #4: com acts_as_fulltextable
      @products4 = (Product.find_fulltext(@kw) + Product.find_fulltext(@kw_phonetized)).uniq.delete_if {|x| x == nil}

    end

    @list = Product.pluck(:title).join(" ").split.uniq.sort

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Soundexo", root_path, :class => 'brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Soundexo"
      %meta{:content => content_for?(:description) ? yield(:description) : "Soundexo", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/products/_form.html.haml
= form_for @product, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn'

app/views/products/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      -# %th= model_class.human_attribute_name(:id)
      %th título
      %th descrição
      -# %th= model_class.human_attribute_name(:created_at)
      %th ação
  %tbody
    = render product

app/views/products/_product.html.haml
%tr
  -# %td= link_to product.id, product_path(product)
  %td
    = highlight product.title, @kw
    %br
    %small= highlight product.title_phonetized, @kw_phonetized
  %td
    = highlight product.description, @kw
    %br
    %small= highlight product.description_phonetized, @kw_phonetized
  -# %td=l product.created_at
  %td
    = link_to edit_product_path(product), :class => 'btn btn-mini' do
      %i.icon-pencil
    = link_to product_path(product), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger' do
      %i.icon-remove.icon-white

app/views/products/edit.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/index.html.haml
- model_class = Product
%form.form-horizontal{action: products_path}
  %input{type: :text, name: :q, placeholder: "Search", value: @kw}
  %button.btn OK
  = link_to "View all", products_path, class: "btn btn-mini"

- if @kw
  .well
    Busca por: #{@kw}
    %br
    Phonetized: #{@kw_phonetized}

.row
  .span12
    %small
      - @list.each do |item|
        = link_to item, products_path(q: item)
  .span6
    .page-header
      %h2
        v3
        %br
        %small Busca com acts_as_indexed
    = render partial: "list", locals: {product: @products3}

  .span6
    .page-header
      %h2
        v4
        %br
        %small Busca com acts_as_fulltextable
    = render partial: "list", locals: {product: @products4}

.row
  .span6
    .page-header
      %h2
        v1
        %br
        %small Busca em qualquer trecho da palavra
    = render partial: "list", locals: {product: @products}

  .span6
    .page-header
      %h2
        v2
        %br
        %small Busca em palavras inteiras
    = render partial: "list", locals: {product: @products2}



%hr

= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary'

app/views/products/new.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/show.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @product.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @product.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'